[2025-10-23T18:39:36.826+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-23T18:39:36.852+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.first_task manual__2025-10-23T18:39:35.774175+00:00 [queued]>
[2025-10-23T18:39:36.863+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.first_task manual__2025-10-23T18:39:35.774175+00:00 [queued]>
[2025-10-23T18:39:36.864+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-10-23T18:39:36.884+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): first_task> on 2025-10-23 18:39:35.774175+00:00
[2025-10-23T18:39:36.893+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=511) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-23T18:39:36.895+0000] {standard_task_runner.py:72} INFO - Started process 512 to run task
[2025-10-23T18:39:36.895+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'first_task', 'manual__2025-10-23T18:39:35.774175+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp_x4opoo1']
[2025-10-23T18:39:36.897+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask first_task
[2025-10-23T18:39:36.985+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.first_task manual__2025-10-23T18:39:35.774175+00:00 [running]> on host c65f76f8d89c
[2025-10-23T18:39:37.110+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T18:39:35.774175+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T18:39:35.774175+00:00'
[2025-10-23T18:39:37.111+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-23T18:39:37.128+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-10-23T18:39:37.129+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task!']
[2025-10-23T18:39:37.146+0000] {subprocess.py:99} INFO - Output:
[2025-10-23T18:39:37.147+0000] {subprocess.py:106} INFO - hello world, this is the first task!
[2025-10-23T18:39:37.148+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-10-23T18:39:37.180+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-23T18:39:37.181+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=first_task, run_id=manual__2025-10-23T18:39:35.774175+00:00, execution_date=20251023T183935, start_date=20251023T183936, end_date=20251023T183937
[2025-10-23T18:39:37.233+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-23T18:39:37.256+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-23T18:39:37.260+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
