[2025-10-23T18:36:51.398+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-23T18:36:51.429+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.first_task manual__2025-10-23T18:36:49.695093+00:00 [queued]>
[2025-10-23T18:36:51.447+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.first_task manual__2025-10-23T18:36:49.695093+00:00 [queued]>
[2025-10-23T18:36:51.448+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-10-23T18:36:51.479+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): first_task> on 2025-10-23 18:36:49.695093+00:00
[2025-10-23T18:36:51.487+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=464) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-23T18:36:51.489+0000] {standard_task_runner.py:72} INFO - Started process 465 to run task
[2025-10-23T18:36:51.488+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'first_task', 'manual__2025-10-23T18:36:49.695093+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpya4ngwm3']
[2025-10-23T18:36:51.490+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask first_task
[2025-10-23T18:36:51.606+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.first_task manual__2025-10-23T18:36:49.695093+00:00 [running]> on host c65f76f8d89c
[2025-10-23T18:36:51.836+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T18:36:49.695093+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T18:36:49.695093+00:00'
[2025-10-23T18:36:51.840+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-23T18:36:51.906+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-10-23T18:36:51.913+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task!']
[2025-10-23T18:36:51.935+0000] {subprocess.py:99} INFO - Output:
[2025-10-23T18:36:51.946+0000] {subprocess.py:106} INFO - hello world, this is the first task!
[2025-10-23T18:36:51.949+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-10-23T18:36:52.072+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-23T18:36:52.075+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=first_task, run_id=manual__2025-10-23T18:36:49.695093+00:00, execution_date=20251023T183649, start_date=20251023T183651, end_date=20251023T183652
[2025-10-23T18:36:52.153+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-23T18:36:52.186+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-23T18:36:52.189+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
