[2025-10-23T18:52:56.148+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-23T18:52:56.169+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.first_task manual__2025-10-23T18:52:54.954753+00:00 [queued]>
[2025-10-23T18:52:56.180+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.first_task manual__2025-10-23T18:52:54.954753+00:00 [queued]>
[2025-10-23T18:52:56.182+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-10-23T18:52:56.201+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): first_task> on 2025-10-23 18:52:54.954753+00:00
[2025-10-23T18:52:56.209+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=723) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-23T18:52:56.211+0000] {standard_task_runner.py:72} INFO - Started process 724 to run task
[2025-10-23T18:52:56.211+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'first_task', 'manual__2025-10-23T18:52:54.954753+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp9pzp59b5']
[2025-10-23T18:52:56.214+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask first_task
[2025-10-23T18:52:56.298+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v4.first_task manual__2025-10-23T18:52:54.954753+00:00 [running]> on host c65f76f8d89c
[2025-10-23T18:52:56.404+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T18:52:54.954753+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T18:52:54.954753+00:00'
[2025-10-23T18:52:56.406+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-23T18:52:56.433+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-10-23T18:52:56.436+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task!']
[2025-10-23T18:52:56.459+0000] {subprocess.py:99} INFO - Output:
[2025-10-23T18:52:56.464+0000] {subprocess.py:106} INFO - hello world, this is the first task!
[2025-10-23T18:52:56.466+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-10-23T18:52:56.502+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-23T18:52:56.503+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=first_task, run_id=manual__2025-10-23T18:52:54.954753+00:00, execution_date=20251023T185254, start_date=20251023T185256, end_date=20251023T185256
[2025-10-23T18:52:56.550+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-23T18:52:56.572+0000] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-10-23T18:52:56.574+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
