[2025-10-23T18:50:08.846+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-23T18:50:08.874+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.second_task manual__2025-10-23T18:50:04.173816+00:00 [queued]>
[2025-10-23T18:50:08.890+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.second_task manual__2025-10-23T18:50:04.173816+00:00 [queued]>
[2025-10-23T18:50:08.891+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-10-23T18:50:08.913+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2025-10-23 18:50:04.173816+00:00
[2025-10-23T18:50:08.926+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=683) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-23T18:50:08.932+0000] {standard_task_runner.py:72} INFO - Started process 685 to run task
[2025-10-23T18:50:08.931+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'second_task', 'manual__2025-10-23T18:50:04.173816+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp_mqaiqul']
[2025-10-23T18:50:08.935+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask second_task
[2025-10-23T18:50:09.037+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v3.second_task manual__2025-10-23T18:50:04.173816+00:00 [running]> on host c65f76f8d89c
[2025-10-23T18:50:09.181+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T18:50:04.173816+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T18:50:04.173816+00:00'
[2025-10-23T18:50:09.183+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-23T18:50:09.219+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-10-23T18:50:09.222+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2025-10-23T18:50:09.242+0000] {subprocess.py:99} INFO - Output:
[2025-10-23T18:50:09.245+0000] {subprocess.py:106} INFO - hey, I am task2 and will be running after task1!
[2025-10-23T18:50:09.246+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-10-23T18:50:09.297+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-23T18:50:09.301+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=second_task, run_id=manual__2025-10-23T18:50:04.173816+00:00, execution_date=20251023T185004, start_date=20251023T185008, end_date=20251023T185009
[2025-10-23T18:50:09.358+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-23T18:50:09.376+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
